[space]
xmin = 0.0
xmax = 1.0
ymin = 0.0
ymax = 1.0
hx = 0.05
hy = 0.05

[time]
t0 = 0.0
tfinal = 0.7
dt = 0.0005
scheme = "ExplicitEuler"

[physics]
rho = 1.0
nu = 0.1

[boundary]
left   = "Dirichlet"
right  = "Dirichlet"
bottom = "Dirichlet"
top    = "Dirichlet"

[output]
results = "results"