[space]
xmin = 0.0
xmax = 2.0      # Canal long pour voir l'allée se développer
ymin = 0.0
ymax = 1.0
hx = 0.01       # Maillage FIN (200x100) pour bien dessiner le rond
hy = 0.01

[time]
t0 = 0.0
tfinal = 10.0   # On laisse tourner longtemps pour voir l'instabilité s'installer
dt = 0.001      # Pas de temps petit pour la précision (CFL = 0.1)
scheme = "ExplicitEuler"

[physics]
rho = 1.0
nu = 0.001      # Viscosité CALIBRÉE pour Re=120 (Allée de von Karman stable)

[boundary]
# --- Entrée (Gauche) ---
left = "Dirichlet"
left_val = 1.0      # Vent constant

# --- Sortie (Droite) ---
right = "Neumann"
right_val = 0.0     # Sortie libre

# --- Parois (Haut/Bas) ---
# "Neumann" = Glissement libre (comme si le mur était très loin)
# Idéal pour éviter que les murs n'interfèrent avec les tourbillons
bottom = "Neumann"
bottom_val = 0.0 
top = "Neumann"
top_val = 0.0

[output]
results = "results"